Update azure-pipelines.yml

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -15,10 +15,6 @@ jobs:
     timeoutInMinutes: 360
     steps:
 
-      - task: UsePythonVersion@0
-        inputs:
-          versionSpec: '3.6'
-
       # Check Python
       - script: |
           setlocal EnableDelayedExpansion
@@ -132,3 +128,103 @@ jobs:
                         qcengine
           conda list
         displayName: "Install conda packages"
+
+      # Install LLVM
+      # Note: LLVM distributed by conda is too old
+      - script: |
+          choco install llvm --version %LLVM_VERSION% --yes
+          set PATH=C:\Program Files\LLVM\bin;%PATH%
+          echo '##vso[task.setvariable variable=PATH]%PATH%'
+          clang-cl --version
+        displayName: "Install LLVM"
+
+      # Install Intel OpenMP import library
+      # NOTE: libiomp5md.lib is located in conda/win/$(mkl.version)
+      - script: |
+          set LIB=$(Build.SourcesDirectory)\conda\win\$(mkl.version);%LIB%
+          echo '##vso[task.setvariable variable=LIB]%LIB%'
+        displayName: "Install Intel OpenMP import library"
+
+      # Configure
+      - script: |
+          setlocal EnableDelayedExpansion
+          call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
+          mkdir build & cd build
+          if "%CMAKE_BUILD_TYPE%"=="Debug" set MAX_AM_ERI=6
+          if "%CMAKE_BUILD_TYPE%"=="Release" set MAX_AM_ERI=8
+          if not defined MAX_AM_ERI exit 1
+          if "%CMAKE_BUILD_TYPE%"=="Debug" set ENABLE_XHOST=OFF
+          if "%CMAKE_BUILD_TYPE%"=="Release" set ENABLE_XHOST=ON
+          if not defined ENABLE_XHOST exit 1
+          cmake -G Ninja ^
+                -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ^
+                -DCMAKE_INSTALL_PREFIX=../install ^
+                -DCMAKE_C_COMPILER=clang-cl ^
+                -DCMAKE_CXX_COMPILER=clang-cl ^
+                -DENABLE_XHOST=!ENABLE_XHOST! ^
+                -DMAX_AM_ERI=!MAX_AM_ERI! ^
+                $(Build.SourcesDirectory)
+        displayName: "Configure Psi4"
+        workingDirectory: $(Build.BinariesDirectory)
+
+      # Build
+      - script: |
+          call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
+          cmake --build . ^
+                --config %CMAKE_BUILD_TYPE% ^
+                -- -j %NUMBER_OF_PROCESSORS%
+        displayName: "Build Psi4"
+        workingDirectory: $(Build.BinariesDirectory)/build
+
+      # Install
+      - script: |
+          call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
+          cmake --build . ^
+                --config %CMAKE_BUILD_TYPE% ^
+                --target install ^
+                -- -j %NUMBER_OF_PROCESSORS%
+        displayName: "Install Psi4"
+        workingDirectory: $(Build.BinariesDirectory)/build
+
+      # Test (OpenMP)
+      # Check if OpenMP configuration had not failed silently
+      - script: |
+          python -c "from psi4 import core; core.set_num_threads(42); assert core.get_num_threads() == 42"
+        displayName: "Test Psi4 (OpenMP)"
+        workingDirectory: $(Build.BinariesDirectory)/install/lib
+
+      # Test (ctest)
+      - script: |
+          setlocal EnableDelayedExpansion
+          if "%CTEST_TYPE%"=="full" set CTEST_TYPE=".*"
+          ctest --build-config %CMAKE_BUILD_TYPE% ^
+                --label-regex !CTEST_TYPE! ^
+                --output-on-failure ^
+                --parallel %NUMBER_OF_PROCESSORS% ^
+                --timeout 3000
+        displayName: "Test Psi4 (ctest $(ctest.type))"
+        workingDirectory: $(Build.BinariesDirectory)/build
+
+      # Test (pytest)
+      - script: |
+          set PATH=$(Build.BinariesDirectory)\install\bin;%PATH%
+          set PYTHONPATH=$(Build.BinariesDirectory)\install\lib;%PYTHONPATH%
+          psi4 --test %PYTEST_TYPE% -n %NUMBER_OF_PROCESSORS%
+        displayName: "Test Psi4 (pytest $(pytest.type))"
+        workingDirectory: $(Build.BinariesDirectory)
+
+      # Build package
+      - script: |
+          set INSTALL_DIR=$(Build.BinariesDirectory)\install
+          conda build --python %PYTHON_VERSION% ^
+                      conda\win
+          copy /y C:\tools\miniconda3\conda-bld\win-64\psi4-*.bz2 $(Build.ArtifactStagingDirectory)
+        condition: and(succeeded(), eq(variables['conda.build'], 'true'))
+        displayName: "Build Psi4 package"
+
+      # Publish package
+      - task: PublishBuildArtifacts@1
+        inputs:
+          artifactName: conda
+        condition: and(succeeded(), eq(variables['conda.build'], 'true'))
+        displayName: "Publish Psi4 package"
